# Cohabiting

In our individualistic Europe we are not really use to get along with each other. We feel stress and pressure if we don’t find our “own moments” along the day, but ironically, we cannot leave our smartphones when we go to the toilet.

In the current situation, it is likely that your time alone, may either get reduced or expanded. In case you live by yourself, you can likely suffer from loneliness at some point. In case you live with flat mates, and family member, you better learn how to communicate with each other effectively as soon as possible. 

In any case, I encourage you to get in contact with your neighbors in a safe way (2-meter distance, no physical contact, wash hands afterwards, etc…). The more social assets and resources you have around, the more access to potential help you will have in case you need it.

## Get to know yourself

Before venturing out to others, you better get familiar with the person you are. If you haven’t realized it yet, you are the person with whom you will spend your whole life. Getting to know oneself should be something all of us do all over our lives. However, in times of crisis, it is especially important that you put some conscious effort into getting to know the voice in your head, you habits, tendencies, moods, tempers, emotion management, coping mechanisms…

Let’s take it bit by bit. 


### Loneliness

I have suffered from loneliness pretty much since I left my hometown and family and I started the university 10 years ago. It is not that I have been alone, but my social needs are very high and my threshold to loneliness, low. I advise you to read [*Loneliness* by Carioppo](https://www.amazon.com/Loneliness-Human-Nature-Social-Connection/dp/0393335283) [@cacioppo2000loneliness], or check his [TED Talk](https://www.youtube.com/watch?v=_0hxl03JoA0).Loneliness is like hunger. It is a way your body and being has to point out that there is a need that is being unfulfilled. If you need water, you are thirsty. If you need food, you are hungry. If you need people, you feel lonely. 

There is nothing bad with it. Just acknowledge it, and take the due action to reverse the situation. Since how to deal with loneliness is beyond the purpose of this guide, one thing you can do if you are lockdown at home and you start feeling lonely too often, is talk with a friend and move to their place (or they to yours). The cohabiting may be challenging and you may miss your moments alone, but on the long term, human beings need shared moments more than the tranquility of loneliness. ^[I also invite you to read my [letter to B.](https://carlitofluito.github.io/letters2019_20/to-b-.html), if you are curious about my loneliness and suffering. ]

### Get in contact with your needs

Different people have different needs. Acknoledge that. In this situation, we are all force to spend whole days locked in one small place. It feels like we are caged animals. We are usually fine with being in cages, but now that it is forced, we feel trapped.

Considering that our needs for fresh air, freedom of movement, and some task to do are heavily reduced, it is fundamental that we enter into contact with our needs in a healthier way. 

Therefore, be aware and conscious of what your body is asking for. If you need to go out because you feel trap at home, consider taking walk on the park on the sunrise, or during the night, when there is no risk of contagion. If your needs asks for human contanct and you feel lonely. Consider spending some days at a friend's place that seems healthy and stable.

Accept your needs and try to fulfill them consciously, minimizing the risks of the situation. It is not possible to go to a bar with many friends, but moving for 3 or 4 days to live with the same friend seems doable for me.

With food, you can try some fasting. Intermitent fasting will make your body more efficient at metabolizing food and it can make your food last longer without negative consequences for you in case things get really, really angry. 

But let's not get too ahead of ourselves yet, and let's talk about current situations. 

### Chronotypes

Your chronotype is the rhythm of your brain along the day. If you feel more awake in the morning, you are and early bird. If you are more awake in the evening, you are an owl. ^[You can learn more reading Daniel Pin’s book [*When: The scientific secrets of perfect timing*](https://www.amazon.com/When-Scientific-Secrets-Perfect-Timing/dp/0735210624) @pink2019scientific]

This is quite important if you are going to share the same space with people with different chronotype than yours. Some people get up filled of energy, some others are angry and slowly until midday. Be aware of what is your case, and understand the differences in others. 

You want to keep things working as smoothly as possible, thus, negotiate your own biological timings. ^[You can also visit my other [guide with life advice](LINKLINKLINK) where I mention the chronotypes.]

### Sleep enough

Your body heals when you sleep. Now that everybody is in lockdown, there is not much to do. Thus, take your time and rest deeply. Lack of sleep weakens your immune system. Thus, make it difficult for the virus, use the opportunity and catch up with sleep. Check some [TED talks](https://www.ted.com/talks/dr_matthew_carter_the_science_of_sleep_and_the_art_of_productivity?language=en) about sleep if you are curious about the needs and the benefits of quality resting time.

### Emotional management

We all are going through many emotions at the moment, from fear, panic, nervousness, anger, worriness, boredom, excitement, confusion, surprise...

Thus, it is fundamental that we learn how to remain calm and don't let our emotions take control of the situation. Specially, when spending long periods of time with other people, we need to learn how to release our emotions in a safe way, avoiding aggressivity, but without letting conflicts unresolved. 

Some basic strategies you can already start reading and learning about are: 

- **Meditation**: There is tons of resource on the internet about how to meditate and what are the benefit and impact on psychological and physical health. You can explore a [post I wrote](https://www.carlitofluitoideas.com/meditation-app/) about selecting the most suitable meditaion app depending your previous experecience as meditator, from complete beginner to energy healer. 

- **Emotional intelligence**: [Daniel Goleman](http://www.danielgoleman.info/) is one of the most famous author on the topic. Also, [Mayer and Salovey] are two respected authors within academia that have researched about the topic for many years. You can read and overview of the theory [here](https://www.verywellmind.com/what-is-emotional-intelligence-2795423). 

Basically, you need to train yourself in the four components of emotional intelligence: perceaving emotions, reasoning with emotions, understanding emotions, and managing your emotions. 

Before you get in an argument during the lockdown, breathe deeply, remember your meditation sessions, and perceive, reason, understand and manage what is going on. 

### Habits and tendencies

Different people have different habits. When living together it can get problematic with your flatmates, but the first thing is to know what are your own habits, and in which self-destructive patterns you can fall. When having a lot of free time, you may binge-watch series, or spend the day without doing much, just fooling around your social media. Therefore, the earlier you stablish a series of healthy habits that keep your mind busy and growing the sooner you will enjoy your lockdown time, and the more you will take out of the situation.

I am writing a post on my site about [my personal habits](www.carlitofluitoideas.com) and how I track them ^[Unplublished for the moment]. Take a look if you need some inspiration. Remember, take advantage of this situation. Imagine that you got some free days to invest in yourself, refresh your skills and upgrade your life. 

### Smartphone fear based

> *Avoid panic mode, go airplane mode.*

If you are alone at your place watching conspiracy videos, it is likely that you start to get paranoid. You may also receive messages and testimonies from people at other countries, or stories about how is the situation in hospitals. In this cases, the more you use the smartphone, the worse your imagination will become. If you are lockdown at your place and you don't have the virus, the worse thing that can happen to you is loneliness and boredom. If you are alone and you develop sympthoms, then wait few days before heading to the hospitals. It is important to give a chance to your organism to recover by yourself before collapsing healthcare system. 

Additionally, fear and worry will lower down your defenses making you more vulnerable to catch the disease. Thus, shut down your smartphone, or set it up in airplane mode and stablish a *"time for myself"* attitude.

### Hypochondriac

You may start to feel some symptoms at some point. Don’t get hypochondriac and run to the hospitals. If you go to a hospital for mild symptomathology, if you don’t have the virus, you will get it there waiting in emergency. Therefore, try to stay at home, breathe in, breathe out, treat yourself specially good for a couple of days, and wait patiently to see how your situation evolves. If you are young, you may go through the COVID-19 with ease: bit of fever, runny nose, diharrea, and cough. Obviously, if you get worse (short of breathe, high fever), it is probably time to go to the hospital. 

However, try to not get panic for nothing. The more you read about the symptoms, the more your mirror neurons will fire, and the more your brain will remember how many times you sneeze in the last 4 hours. Relax. If you started the lockdown on times, chances are that you are safe. 

Also, it is important to know that catching the virus is not cool, it is dangerous. A health worker [made a video]( https://www.instagram.com/p/B9sFEHzHHqF/?hl=en) where he asks Spanish youth to stay at home and avoid collapsing hospitals for weak symptoms. He implies that some people just go there to “check” if they have the virus to post it on their social media. Please, don’t be stupid. Stay at home, avoid collapsing the hospitals, and spend your time continuing reading this guide. 

### Be creative, keep yourself busy

Use the opportunity to delve in your own creativity. Check the book [*The artist way* by Julia Cameron]( https://juliacameronlive.com/books-by-julia/the-artists-way-a-spiritual-path-to-higher-creativity/) [@cameron2016artist]. In this book, you will find a series of creative exercises and self-exploration that will keep you busy exploring your own creativity during the lockdown. 

Also, use the occasion to think outside of the box. Creativity sparks with limitations. Creativity is based on new connections of old elements.  Now, that you cannot escape your room, take the opportunity of mixing things up, came up with new ideas, and use develop that artistic passion that you never could. 

### Make a schedule

You need to keep yourself organized. [Jordan Peterson]( https://www.jordanbpeterson.com/) mentions the duality between chaos and order in their works *Maps of meaning* @peterson1999maps and *12 Rules for life* @peterson201812. When there is too much chaos in one’s life, psyches collapse. When they have too much order, people need to fly away. 

In our current situation, it can happen both at the same time. There is too much new chaos in our lives because our plans for March and April got cancelled, and at the same time there is too much order because we cannot escape the environment where we are trapped in. 

Therefore, try to find a balance in between. Use the chaos opportunity to put order and establish a schedule of your day to day of quarantine and use the ordered environment to explore the inner chaos of your psyche, your room, and maybe ending up ordering the world a bit more. 

Furthermore, having and following a schedule will serve as an anchor and guide through your days of quarantine. It is very easy to stop doing things, fall into self-destructive patterns, over-sleeping, compulsive video-gaming, binge-watching, and ending up with a worse life than before. However, if you organize yourself, make a morning routine connecting with your body, your mind, and your long-term working strategy, the quarantine period can become an unforgettable moment of thriving and upgrade of your current life. Use it wisely. 

### Drop individualism

Even if you are alone at home, you should stop thinking as an individual. Here in Europe, we are use to have our own personal time and space, but the current circumstances are asking for something different. Think of yourself as a piece of a huge mechanism. Whatever you do will have an effect on the whole system. Therefore, follow security guidelines, stay at home, avoid hospitals as much as possible, and try to help your flat mates and your neighbors. 

Contrary to what apocalyptic artwork suggest, human beings behave at their best in the worst situations. This brings the best of human nature. The cooperation, kindness, responsibility, solidarity, altruism, and generosity that makes us the ruling specie in the planet. Don’t enter into fear, and let the panic take rule of the situation. Don’t fight over toilet paper on the supermarket and think whether the resources you are taking can help other person more than you. 
Help those in need. If you have grandparent, or elderly in your proximity, offer them shopping and cleaning their house. Keep them as safe as possible. We will survive this all together. Focus on the love, focus on the cooperation, and drop fear, egoism, and individualism. 


## Get to know each other

If you are cohabiting with other people, you have an excellent opportunity to get to know them better; to learn and discover about different life approaches and perspectives; to deepen in your relationship. You can ask deeper questions, brought more original topics, and make yourself more vulnerable. About social connection and vulnerability, it is likely that you have heard about [Brene Brown](https://brenebrown.com/) and her [TED Talk](https://www.ted.com/talks/brene_brown_the_power_of_vulnerability?language=en). 

Go a bit deeper in yourself, expose your soul and connect with those around you.

### Extremelly needed non-violent communication

During the lockdown time, you'll have to learn how to talk with each other. When small problems and conflicts are left unspoken, the negative feelings and sensations accumulate in one's body, and that negative energy is carried throughout the day. It is possible to sense the tension when there has been a conflictive situation where one of the parts hasn’t spoken their mind. Avoid keeping things inside and seek to express them in an effective and non-aggressive way. 

You can learn about [non-violent communication]( https://www.cnvc.org/) to avoid saying things like: *You are always telling me what to do and what not to do*, or *You never listen to what I say*. With some basic guidelines you can switch these messages to: *I often feel that you tell me what to do and what not to do. I would thank you wouldn’t do it*, or *I don’t feel listened when I talk with you*. 

Keep in mind the communicative attitude and assume that the other people are trying to do their best as well. You can remember those sentences of: *We are all lost individuals trying to figure out what to do with our lives*. Or use strategies like imagine the person that is arguing with you when they were small kid or baby. This way, you will reconnect with your empathy and kindness and try to bring back the problem solving mood to the situation. 
 
#### Straight forwardness

Although, it may sound contradictory with the non-violent communication, my type of personality (ADHD), thanks and welcomes straight forwardness. I really appreciate when people say things clearly, even if they can be harmful at the moment. I also drop much of my ego when I am talking or receiving feedback. It can sound a bit advance to try to detach from your creations, your thoughts, your body, or even your “self” or identity; but it is a wonderful way of listening more clearly and without judgments to what people are actually saying and meaning. 

Try to ask for clarification as much as possible to avoid misunderstandings, if you are confused about what a person mean, ask them. Also, you can point out inaccuracies and polarization terms, like always or never, all the time, the whole day, everything, everyone… None of us is able to do everything in the same way. Thus, avoid using inaccurate sentences, and aim to reach a truthful communicative level of speech. 

Challenge yourself and dear to say things more directly. You can check the *security word* strategy below to offer the person you are talking with a way of soothing down your speech, in case is too much for them. 


#### Assume good will and be cooperative attitude

If you are not living with a toxic person^[I suffer myself from a toxic relationship. If you are curious, click [here](https://carlitofluito.github.io/A/).] (psychopath, sociopath, narcissist, or borderline personality), you can assume that the other people aim to have a peaceful and relaxed environment. Many of us are not very good at managing our own emotions, and when we suffer from stress, we can become harsh and a bit evil. However, it is fundamental to keep in mind that evil comes from suffering, and when someone behaves with bad intentions, they are likely trying to make others experience the suffering they hold inside. 

Thus, thanks to your meditation practice, you will be able to remain chill and cool if the situations heats up and observe reality in a more objective way without loosing the perspective. Remember that most of us just want the best for ourselves and others. You can research a bit about [Pygmalion effect](https://en.wikipedia.org/wiki/Pygmalion_effect) and discover how beliefs can determine behavior. Thus, have a positive belief, assume goodness and cooperation, and you may create your own reality. 


#### Be empathetic

People like me can come across too harshly. We have good intentions, but sometimes we forget about who we are talking to, and we can be harmful. Thus, remember to be empathetic. Acknowledge your infinity ignorance about the other person’s state of consciousness. All of us have gone through a personal life process full of suffering. Our own unique experience and leanings have made us the way we are, so, it is normal that we don’t understand each other. We are all *f\*cking talking monkeys* trying to understand each other. Nothing else. 

A simple practice to develop your empathy, is to try to *tune in* with the other person. Just look into their eyes, breathe deeply a couple of times, and try to observe them without judgements. Imagine a recent suffering they may have gone through, and keep your awareness on the present moment, your own body and the person in front of you. In this way, you may be able to connect with the other state of being and adapt your speech and intensity to the other person. 

### Express your needs and limits

One of the things I learn from [my toxic relationship]( https://carlitofluito.github.io/A/) was to express my needs clearly and out loud. The more you are in contact with your needs and limits, the easier will be to share them. With non-violent communication, you will be able to express them in a way that is not aggressive, but assertive, spoken out your mind with clarity and self-respect. 

Your flat mates, friends, and relatives cannot read your mind. They cannot know what you think or how you feel. You need to remain communicative, and cooperative, speaking clearly what you need. Sometimes it is difficult to verbalize, and you may not know what do you need or want. In these cases, speak your communicative difficulties as well. Tell them that you are unable to speak at the moment, that you need some time to reflect and understand yourself, and that there is nothing wrong with them or the relationship. 

### Time alone

In WEIRD cultures^[Western, Educated, Industrialized, Rich, and Democratic]  [@henrich2010weirdest] like ours, we are used to have our own private space and personal time. In more collectivistic and developing countries, the story is different. The density of population is so big that people are force to adapt their individualistic impulses to the dynamics of the group. 

In situations like the one we are living, it is a pretty efficient strategy to adopt a "developing country" mindset as soon as possible. We will be together, we will have to share personal and private spaces and resources, and we will be forced to collaborate and sacrifice our personal desired in favour of the collective.

Anyways, if too much cohabiting gets complicate, you can set up a house rule for taking *"Time alone"*. My advice here is that you make it fully "**Time Alone**". I am inspired in the practice of taking one day of [*dopamine fasting*](https://www.youtube.com/watch?v=vl-44jDYDJQ&t=339s), when you are not supposed to eat, socialize, read, use your devices, etc... You can set up a 2 to 3 hours of full time alone, when one person can enter a room without any distraction or devices, so he can focus exclusively on meditating, calming themselves down, write something, exercising, or processing the situation. 

I also advice you to adopt the **silent hour** strategy. For this, you may make an agreement with your flatmates/relatives/yourself, of remaining completely quiet for an hour (thoughts included). It is a shorter version of the *vow of silence* observed by many religious traditions, and practiced by monks and nuns in spiritual retreats. Give it a try.

### Be kind

For maintaining a healthy environment, it is necessary cooperation, and collaboration. The desired attitude to develop in these conditions is a kind approach to others. Kindness is the ability of remain receptive and responsive to other’s need. Words like generosity, patience, tolerance, humility, or empathetic listening are all elements of what kind may mean. 

#### Be helpful, prosocial, altruist

There will be a continuous flow of things to do and to be done. You can try to keep an organic functioning, without explicitly sharing house chores. However, if things stop working, make a schedule and share chores. 

In case you prefer to go more organic, without a clear schedule and reacting to the different needs of the house; I suggest you start with a collective *deep cleaning* of the whole house, and then try to maintain that level of order. It will be much easier. 

Once the whole thing is clean and airy, you can just be helpful with each other. In a funny way, you can do the dishes, and cook collaboratively. Similarly, when one of you is, for example, making the laundry, or cleaning around, you can spontaneously offer your help. Everyone welcomes [*random acts of kindness*]( https://www.randomactsofkindness.org/kindness-ideas), and [scientific research]( https://www.sciencedirect.com/science/article/pii/S0022103117303451) back up how beneficial is for your well-being. [@curry2018happy]

- **Use your sense of humour**. Don't



#### Respect each other processes


### Negotiation

#### Norms and rules for smooth collaboration

- **Levels of order**

- **Silent hour**

- **Security word**


## Check with your neighboors


### Make initial contact

### Help them with shooping, errands 

### Avoid isolating elderly


