# Logistics

By now, it is likely that you already have a system about how to do the things you have to do. However, reading this section, you may find some tips and advice to implement to your system, or some new strategies that can improve the efficiency of certain tasks, or bring awareness to new aspects that you didn’t consider before. 

Many of the things I suggest, depends ultimately on your national laws. In countries like Spain, the lockdown doesn’t allow people to go outside home for exercising, while in Belgium or Germany you can go out alone, and even with flat mates. Thus, consider to take my general advice and modify it according to your needs and possibilities. 


## Groceries

As everyone else from our specie, you need food to survive and thrive. Once upon a time, we used to live as nomadic hunter-gathered groups of maximum 150 individuals. Nowadays, we are isolated in our big houses, walking to the supermarket when the hunger appears, and hunting around the shelves, and gathering items in the shopping cart. However, situations like the current lockdown we are living may connect us with a survival instinct that we better acknowledge and control. 

You may start reading [this short article](https://www.weforum.org/agenda/2020/03/supermarkets-grocery-coronavirus-covid19-supply/) to gain a bit of perspective in the whole situation.  

### Non-perishables

First pretty obvious thing that you have likely realized is that there are perishable and non-perishable foods. Perishable foods are the one that gets spoiled after few days, even when it is in the refrigerator. Non-perishable ones those you can forget on the cupboards of your kitchen randomly finding them after months, or even years. 

One thing you should be aware of is that China hasn’t run out of food in the whole time of its lockdown (more than 4 months). Thus, it may be of common sense to think that things are going to be okay if people don’t store half supermarket at their kitchen. I suggest you to buy as you would normally do. Maybe, in a bit bigger quantity, to reduce the trips to the store, but don’t overload yourself. Specially, don’t overload of perishable foods. 

As a wannabe fruitarian (vegan most of the time), fresh fruits and vegetables are my main source of maintenance. Thus, I don’t mind when I arrive to the supermarket and the pasta and bread are finished, but I can get a bit pissed if there is shortage of vegetables. Thus, buy consciously for 3 or 4 days. Think that you will need a excuse to leave your house sooner or later, and going to the supermarket will be a good one.

Just chill down and enjoy the situation. Vulnerable groups are the ones that have to stay at home and take special measures, but if 80% of the cases are going to develop mild flu symptomatology from fighting the virus, you can likely drop panic and focus on thriving. 

If you are concerned, buy some significative amount of non-perishable foods, from grains and seeds (pasta, rice, quinoa, beans), to root vegetables (batata, potato, yuca, beetroot). You can also buy some vegetable milk, and juices. However, I suggest to get non-processed foods as much as possible, since they are the easiest to produce. In case, the factories stop, the supplies that will finish first will be the ones of processed food. Thus, stay simple and safe. Buy the basics and spend some extra-time cooking at home with your loved ones, you will enjoy the process. 

You can also buy some frozen vegetables or frozen them yourself. Consider cleaning up your fridge and freezer before doing so to guarantee that you have enough space for all your shopping. 

If you are an omnivore, I seriously advice you to drop meat. Not only for [the animal suffering]( https://animalequality.org/news/why-factory-farming-is-the-largest-cause-of-animal-abuse-in-history/), [the environmental cost]( https://en.wikipedia.org/wiki/Environmental_impact_of_meat_production), and the [negative effects to your own health]( https://www.ncbi.nlm.nih.gov/pubmed/26780279); but also because meat consumption is the [origin of many pandemics and diseases]( https://www.aljazeera.com/indepth/interactive/2020/02/deadly-viral-outbreaks-originated-animals-200205173647803.html), and the [antibiotics resistance]( https://www.facebook.com/1743390035906798/videos/639756720177289/) that will make the COVID-19 pandemic look like a cloudy day at the beach. Be serious and be responsible, drop meat, and ditch milk. Going vegan nowadays it is incredibly easy and yummy. Now that you know it, not doing it is an act of selfish hedonism and lack of solidarity with all beings of the planet, you included. 

### Different supermarkets

Seems intelligent to me to go to different supermarkets when you go shopping. Althouhg, it is true that you may expose yourself more to the virus, you will avoid panic and emptying shelves, which seems more relevant from my point of view. Besides, depending on the degree of severity of the lockdown in your city, having several excuses to be outside of your place for a longer time, seems an extra argument. 

Obviously, take the security measures you consider, from wearing a mask and gloves, to wash your hands thoroughly and changing your clothes once you arrive home. Nevertheless, as I have pointed out, from my point of view, it is vulnerable people the ones that have to be extra-careful with the spread and contagion of the virus. The rest of us, taking some security measures, should be able to carry out a more or less normal life while the pandemic passes by. 

Therefore, don’t empty shelves, buy enough for 3 or 4 days (not for 3-4 weeks), and try to live your life as normal as possible.^[And of course, move towards a more vegetarian, vegan, or frugivore diet.]

### Personal hygiene products

In the next section, you can find some words and ideas concerning personal hygiene products, toilet paper included. 


## Transportation

Transportation is a need that every person has. During this lockdown period, this need is highly reduced, since we are supposed to stay at home. However, we all still need to go shopping, go to the hospital if needed, and escape to our parent’s place if we cannot afford the rent anymore. Following, I suggest you a couple of ideas, and security measures, you may want to implement. 

### Avoid going out

First of all, as I bet you already know, avoid going out, #stayathome. I have my personal skepticism about how reasonable the measure of locking everyone is. Conscious social distancing and focus on the vulnerable populations seems a more adjusted measure for the type of virus we are facing^[If it would be evola, or SARS, it would be a different story.]. Anyway, but I can happily comply to the law in this case.

Since you have to stay at home, try to use your trips outside your house as consciously as possible. Take the garbage out, make some groceries, bring the shopping to the elderly around, go to the pharmacy, and fix some papers from the unemployment governmental help. All at once. This way, you will keep on reducing the pollution on the cities, and you will avoid getting a fine from the local authorities. However, if you have to move, there are better ways of doing it.

### Walk or cycle

I am very bad at walking. I don’t know how to walk without getting impatient. I am not the type of person that could simply go out for having a walk, and I always have the feeling that I am arriving late when I have to walk to places. That is why, I am always on the bike. Biking is for me the perfect balance between speed and pollution. Cycling has a virtually non-existing impact on pollution levels on cities, while allows you to reach destinations 3 times faster than walking, and depending on the city, in as much time as a private car, and normally a bit faster than public transportation. Thus, with corona or without corona, use a bike. 

Just be careful of not having an accident, since none of us wants to go to a hospital these days. With a bike, you may even be able to escape the city and spend some time in the nature where police is less likely to find and fine you for not being at your place. I am the type of person that prioritizes consciousness over laws and regulations. The risk of cycling to a big park or forest nearby, and spend some time alone in the nature, given the conditions of the current pandemic are pretty nonexistent. Thus, I suggest you get a bike, and enjoy the beginning of the spring admiring nature with your own eyes. 

### Cars and motorbike rental

If you have a private car, you can use it for shopping and doing groceries. Remember the advice about offering your car and the trip to the groceries to help your neighbors and elderly with the shopping. However, you may find useful to rent a motorbike or a car for a given trip.^[Imagine that you plan to paint and fix the house, and you have to buy several paint cans and some tools and materials.]

In this cases, a rental car will help you with the operation. My suggestion here is that you take some extra measures. You can wear gloves, clean a bit with a cloth, and be sure you are not touching your nose, mouth, and eyes during the trip. Otherwise, try to use the trip to do as many things as possible all at once. Make a list beforehand to be sure that you are not forgetting anything.  

### Public transport

It is likely that you already know what to do and what not to do in public transportation. Avoid touching with your hands around the vehicle. Use your wrists and elbows as much as possible to press buttons and open doors. Don’t touch your face and eyes during the trip, and if you cough or sneeze, do it in your elbow. 

Public transportation it is likely one of the most contagious form of moving around the city. A closed environment shared temporarily by numerous anonymous non-related people. Thus, take it just when necessary, and take extra security and hygiene measueres, before, during and after using it. 

## Garbage management

I don’t think that the system will collapse to the point that garbage management stops. However, it is a good opportunity to be extra conscious about how much waste we produce. If you buy fresh fruits and vegetables, it is likely that you are close to become a zero-waste person. The more processed products you buy, the more likely they came in plastic packaging. It is understandable that cleaning products need a package. However, consider squeezing and compressing your garbage as much as possible, to reduce the amount and volume of waste you produce. 

Similarly, having plenty of free time, you can get serious about home recycling. You can start separating plastics, papers, and organic food, and maybe ending up making your own compost with the peels of fruits and vegetables for feeding your plants at home. 

Think about the people that are still working during the lockdown and keep the parts of the system that are still running as functional as possible. 

## Communication 

It is 2020. We are lockdown because of a pandemic caused by a coronavirus that produces mild flu symptoms in 80% of the population. Water and energy systems are working, and since this guide is digitally written and published, I assume you have access to internet and, at least, an electronic device. Thus, it is not a war, there hasn’t been a supernova radiation frying up every chip on the planet^[I love to observe the bigger picture of our fragile existence from time to time.], and the pandemic is not mutating the infected ones into brain-suckers. 

There is no need on entering panic mode and contacting your family and friends every 10 minutes to ask how they are. It is true that there is more free time to catch up with old friends, but it is also pointless to collapse communication networks because we are video calling for 3 hours. I trust on your awareness and responsibility, and I suggest you connect with the people you have been lockdown with. Also, you can use the opportunity to download a book from the [World Digital Library]( https://www.wdl.org/en/) and catch up with the classics.^[Check the *Free Time* section for more ideas about what to do during this lockdown period.] 

