---
title: "How to thrive with COVID-19: The guide "
author: "Carlos Alcala a.k.a. Carlito Fluito from the.corona.guys"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: "bibliography.bib"
biblio-style: "apalike"
link-citations: yes
github-repo: carlitofluito/thrive_covid
description: "An updated reference guide with a compilation of strategies not only to survive the corona crisis but to thrive as a species thanks to the Covid_19"
---

# Preface {-}

> Corona times require corona measures.
>
> *Carlito Fluito* 




My name is Carlos Alcala, a.k.a Carlito Fluito. Like many of us, I had plans for March and April. Traveling, visiting some friends in different countries… However, now I am locked down in Berlin.



The moon looks beautiful though.



It is the first time in human history that we are living a situation like this. We have never had access to the current level of digital communication, and we have also never faced a pandemic of the dimensions of the current situation. Globalization has made the Covid_19 spread with speed and effectiveness that couldn’t have been possible before airplanes, just 70 years ago. Therefore, this is not a problem only effecting specific countries or individuals, this is a crisis regarding all of humankind; a bunch of talking apes stuck on a rock in a planet somewhere in the universe.



A crisis is an opportunity. If we collaborate, develop a sense of global communitarianism, and behave properly, Covid_19 may enter history for being the trigger point that made our species survive as a whole and reversed the apocalyptic tendencies that human behavior was creating.



The apocalypse didn’t arrive with Covid_19, the apocalypse was coming already. Covid_19 is just a wonderful opportunity to restructure our hierarchy of values and connect back to our true nature, what we really are; talking apes trying to understand each other.  



Let’s use this opportunity to realize that an alternative system is possible. A system where we are living guided by our needs and a communal urge to help and take care of each other.



The sky is beautifully blue in Berlin. The moon moved, the planet moved.



## This guide {-}

This guide is a document that will be in constant update. Therefore, whatever suggestion you have, please, contact [*the.corona.guys*](https://www.instagram.com/the.corona.guys/?hl=en) or [Carlito Fluito](https://www.instagram.com/carlitofluito/?hl=en), and we’ll do our best to make modifications, and add valuable information.



The guide is envisioned to offer some advice and a strategy for not only surviving but thriving out of the current situation. I have biases. As a European that is locked down at Berlin, I have been raised in an individualist mindset, surrounded by material wealth, high levels of comfort and security, and within an established government that cares for human rights. We are the lucky ones in the world. Many other people are in conditions far worse than ours. Remain grateful.



By the end of the guide, you should know, what to do and how to respond to the first days of the lockdown: how to make it as difficult as possible to contract the virus, how to organize in small groups, how to communicate and negotiate effectively in order to avoid conflicts in stressful situations, where to get informed without panicking, and how you can use this as a huge opportunity to thrive as a human being and as Sapiens.



The more people can read this guide, the faster we’ll move to a more promising outcome for all of us; and the faster we’ll change the situation not only in the short-term during and after the lockdown; but also, years and years beyond, where we remember the Covid_19 as the beginning of a more sustainable and humane way of living on planet earth.


If you want to help me as individual, writer and dancer, you can support me on [Patreon](https://www.patreon.com/carlitofluito)^[Today is 2020-03-21 and I have 0 supporters. You may want to be the first :-)] As many others, my current income is 0€ per month. However, I hope I am bringing some value to the whole society. If you want to reward me, you can. ^[I also much appreciate *Thank you* emails.]


## The setup {-}



This is a whole new situation for many of us. The stress response is commonly divided into three groups: fight, flight, or paralyze. Physically fighting is not possible, because a virus is not a tangible thing we can attack corporally. Flight is making many people travel back to their countries of origin, to stay with family and beloved ones, which is unfortunately increasing the risk of propagation of the pandemic. Ironically, the paralyzing situation that many of us are in is the most effective way of fighting.



We have to change fear for love. The current paralysis can become a huge leap forward if we take this new communitarian approach to the situation.



## The goal {-}



As you have probably heard, the goal now is to flatten the curve. Things don’t look too ugly at the moment, and we don’t want things to get uglier; however, they can. Check [Tomas Pueyo’s article]( https://medium.com/@tomaspueyo/coronavirus-act-today-or-people-will-die-f4d3d9cd99ca) while I am writing the guide. You will get an idea of why it is necessary that everybody collaborates and stays at home. We don’t want to collapse the whole system. It is important that we are conscious of what is going on and what is coming.



We, all of us, have to act now. Stay at home, keep reading.




