# Three possible post-COVID scenarios

The world is being shaken by a pandemic. Our lives and the way we function as a species were already in a process of fast change before COVID-19 hit us globally. However, it makes sense to believe that under the current circumstances, things are going to change faster than we expected, and possibly in unexpected ways. 

With this text, I would simply like to spark some questions and reflections among the population to question where are we moving forward and how we can use the current weird circumstances to take hold of the situation and move towards a better planet for everyone. 

The text is sparked by the readings and prediction of other authors as Harari [@harari2020world, @harari2016homo], some [David Icke’s](https://en.wikipedia.org/wiki/David_Icke) ideas. I am also inspired by utopias and anti-utopian words as Orwell [@george20071984], Huxley [@huxley2007brave], or Bradbury’s [@bradbury2012fahrenheit]. Also, some pop culture, films and series like Elysium [@elysium2013], Black Mirror [@blackmirror], or Years and Years [@yearsandyears]. I also check newspapers and other articles that I may and may not quote along with the text.


## Introduction

If you don’t have time to read the whole thing, here is a summary, straight to the point, and sacrificing in literary style. 

The three scenarios are: 

**1. Neo-draconian technocracy:**

In this scenario, there is a central government with lots of power, control and information over the population. Something like China. About the character of the government, hostile or benign, it is still unsure.  

-	**Government**: Authoritarian government by technocrats and artificial intelligence. Eventually, the artificial intelligence will take over completely.
-	**Control**: Remote control of citizenship behavior, thoughts, and physiological functioning through technology. Monitoring devices like smartphones, then wearables, eventually microchipping under the skin.
-	**Economy**: Combined control of economy based on a capitalist market that can be overtaken by the government at any moment. Potential universal basic income needed. 
    -	*Benign outcome*: automatization of jobs will free up workers, giving them more free time. 
    - *Hostile outcome*: leaving workers useless and irrelevant. 
-	**Social stratification and services**: Depends if the government is focused on the general population or the wealthy minorities. 
    - *Benign outcome*: basic services are centralized and freely accessible (Education, health, water and energy supply). 
    - *Hostile outcome*: services are privatized, and the government supports owners of mega-companies. 
-	**Wellbeing**: Psychological problems if people remain individualistic and isolated, or psychological well-being if the government promotes social gatherings and group events matching people with affinities using the information collected through the devices. 
-	**Rights**: Sacrifices in individual freedom like freedom of speech, of mobility, of the press, political dissidence. 
-	**Dwelling**: People living in mega-cities managed with the help of artificial intelligence.


Examples and sources of inspiration: 

-	Books: *Brave New World*, *1984*, *Homo Deus*
-	Series: *Black Mirror*, *Years and years*
-	Films: *Elysium*

**2. Utohippiesh and techno-confederation.** 

In this scenario, there is a multitude of eco-villages (best case: less than 150 people), self-managed, autonomous, self-sufficient, and as independent as possible. There is also a confederate government (technocrats helped by artificial intelligence) to offer more technological dependent services (modern medicine, air transportation) and a moral framework (general human rights regulation). I assume the benign character of the confederation and its functioning based on volunteers or compulsory military service (e.g. if there is need of doctors, it will request doctors from communities.)

-	**Government**: Self-managed by the eco-villages. Organic systems of regulation among individuals, like in pre-civilization communities. The confederation checks human rights standards.
-	**Control**: eco-villages can decide whether they want to be tracked to improve aspects of their lives and feed the confederate artificial intelligence; or not, and live more naturally. 
-	**Economy**: Circular economy, without money, and self-managed by the community. Minimalistic, non-consumerist lifestyle. Work is more of a choice than a need. Time to develop passions, tackle human potential, and contribute with valuable creations to the community. The individual can join the confederation to contribute globally. There can be a capitalistic exchange of online services where different communities sell their product to other communities to finance the central confederation services. 
-	**Social stratification and services**: Egalitarianism and shared resources in the communities. Self-managed, free, open education (internet), water and energy supply. Focus on healthy habits to avoid sickness (e.g. plant-based diet, exercise). Confederation offers hospitals when in need. 
-	**Wellbeing**: Psychological flourishing. Individuals can choose whether they want to remain in a community or move to another. 
-	**Rights**: Human rights checked by the confederation. Communities offering freedom and opportunities to individuals.
-	**Dwelling**: People living in eco-construction (e.g. super adobe) in the communities. The confederation has buildings for centralized workers (e.g. workers, engineers…). 

Examples and sources of inspiration: 

-	Books: *Civilized to death*, *Utopia*
-	Series: 
-	Films: *La belle Verte*

**3. Cautious mediocrity**

In this scenario, things come back to (more or less) “*normality*”. Countries are countries doing their things in their own style. 

-	**Government**: Actual democracies moving to more draconian, higher control over the populations; autocracies subjugating more and impoverishing the vulnerable populations. 
-	**Government**: Bureaucracy and unprepared politicians ruling. Not fully functional, and disorganized. Some improvements learned due to the pandemic, but future disasters will happen. 
-	**Control**: Governments will have some more control over citizenship, but individual aspects will remain. Private mega-companies will use individual information for tracking purposes that may sell to governments. 
-	**Economy**: Capitalism is sustained with universal basic income and the help of governments. Automatization of jobs will lead to a work displacement crisis. 
-	**Social stratification and services**: Rich and poor. If basic services are privatized, future disasters will keep on damaging the vulnerable population. If they are public, and badly organized, individuals may lose their trust in the services. The trend till now was privatization and stronger differentiation of social classes, but the pandemic may reverse the tendency.
-	**Wellbeing**: Psychological ailments due to loneliness, stress, and burn-out going on. Prioritization of the system over the individual. Alienation.  
-	**Rights**: Attempt of accomplishing human rights, but limited by the state of markets and the recourses of the government. 
-	**Dwelling**: People living in blocks of apartments in cities. More technological and automatized infrastructure.

Examples and sources of inspiration: 

Newspapers and the capitalistic system.

-	Books: 
-	Series: *Years and years*
-	Films: *In time*


